import { Animal, Investment } from './types';

export const DEMO_ANIMALS: Animal[] = [
  {
    id: '1',
    farmer_id: 'f1',
    name: 'Akboz',
    type: 'cow',
    price: 250000,
    expected_return_pct: 18,
    duration_months: 8,
    status: 'available',
    image_url: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=600&q=80',
    description: 'Healthy Kazakh white cow, 3 years old. Raised on open pasture in Almaty region.',
    slots_total: 5,
    slots_filled: 2,
    created_at: '2026-03-01',
    farmer: {
      id: 'f1',
      user_id: 'u1',
      farm_name: 'Жайлау Фермасы',
      location: 'Almaty Region',
      description: 'Family farm with 15 years of experience',
      verified: true,
    },
  },
  {
    id: '2',
    farmer_id: 'f2',
    name: 'Qarabas',
    type: 'cow',
    price: 320000,
    expected_return_pct: 22,
    duration_months: 12,
    status: 'available',
    image_url: 'https://images.unsplash.com/photo-1546445930-3e6a0a6b2b1a?w=600&q=80',
    description: 'Black Angus bull calf, premium breed. High demand at Qaraghandy markets.',
    slots_total: 4,
    slots_filled: 1,
    created_at: '2026-03-05',
    farmer: {
      id: 'f2',
      user_id: 'u2',
      farm_name: 'Сарыарқа Мал',
      location: 'Karaganda Region',
      description: 'Certified organic farm, 20+ years in livestock',
      verified: true,
    },
  },
  {
    id: '3',
    farmer_id: 'f1',
    name: 'Ақ Жол',
    type: 'sheep',
    price: 80000,
    expected_return_pct: 15,
    duration_months: 6,
    status: 'available',
    image_url: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600&q=80',
    description: 'Merino sheep, premium wool and meat quality. Short investment cycle.',
    slots_total: 10,
    slots_filled: 4,
    created_at: '2026-03-08',
    farmer: {
      id: 'f1',
      user_id: 'u1',
      farm_name: 'Жайлау Фермасы',
      location: 'Almaty Region',
      description: 'Family farm with 15 years of experience',
      verified: true,
    },
  },
  {
    id: '4',
    farmer_id: 'f3',
    name: 'Тұлпар',
    type: 'horse',
    price: 600000,
    expected_return_pct: 25,
    duration_months: 18,
    status: 'available',
    image_url: 'https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=600&q=80',
    description: 'Thoroughbred Kazakhstan steppe horse. Premium asset with high resale value.',
    slots_total: 3,
    slots_filled: 0,
    created_at: '2026-03-10',
    farmer: {
      id: 'f3',
      user_id: 'u3',
      farm_name: 'Байтерек Конеферма',
      location: 'Astana Region',
      description: 'Specialized horse breeding farm',
      verified: true,
    },
  },
  {
    id: '5',
    farmer_id: 'f2',
    name: 'Нұрлан',
    type: 'goat',
    price: 65000,
    expected_return_pct: 14,
    duration_months: 5,
    status: 'growing',
    image_url: 'https://images.unsplash.com/photo-1524024973431-2ad916746881?w=600&q=80',
    description: 'Dairy goat, high milk yield. Quick return investment cycle.',
    slots_total: 8,
    slots_filled: 8,
    created_at: '2026-02-01',
    farmer: {
      id: 'f2',
      user_id: 'u2',
      farm_name: 'Сарыарқа Мал',
      location: 'Karaganda Region',
      description: 'Certified organic farm, 20+ years in livestock',
      verified: true,
    },
  },
  {
    id: '6',
    farmer_id: 'f3',
    name: 'Боран',
    type: 'camel',
    price: 450000,
    expected_return_pct: 20,
    duration_months: 14,
    status: 'available',
    image_url: 'https://images.unsplash.com/photo-1509731987499-fd9bba3a46cc?w=600&q=80',
    description: 'Young Bactrian camel. Highly valued for milk, wool, and transport.',
    slots_total: 4,
    slots_filled: 1,
    created_at: '2026-03-12',
    farmer: {
      id: 'f3',
      user_id: 'u3',
      farm_name: 'Байтерек Конеферма',
      location: 'Astana Region',
      description: 'Specialized horse breeding farm',
      verified: true,
    },
  },
];

export const DEMO_INVESTMENTS: Investment[] = [
  {
    id: 'inv1',
    investor_id: 'current',
    animal_id: '1',
    amount: 50000,
    profit_share_pct: 70,
    status: 'active',
    expected_return: 59000,
    actual_return: null,
    invested_at: '2026-03-15',
    completed_at: null,
    animal: DEMO_ANIMALS[0],
  },
  {
    id: 'inv2',
    investor_id: 'current',
    animal_id: '3',
    amount: 80000,
    profit_share_pct: 70,
    status: 'active',
    expected_return: 92000,
    actual_return: null,
    invested_at: '2026-03-20',
    completed_at: null,
    animal: DEMO_ANIMALS[2],
  },
  {
    id: 'inv3',
    investor_id: 'current',
    animal_id: '5',
    amount: 65000,
    profit_share_pct: 70,
    status: 'completed',
    expected_return: 74750,
    actual_return: 76000,
    invested_at: '2025-09-01',
    completed_at: '2026-02-01',
    animal: DEMO_ANIMALS[4],
  },
];
